// <auto-generated />
using System.Numerics;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieRestful.Repository;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MovieRestful.Repository.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MovieRestful.Core.Models.Movie", b =>
                {
                    b.Property<BigInteger>("id")
                        .HasColumnType("numeric");

                    b.Property<string>("adult")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("belongs_to_collection")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("budget")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("genres")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("homepage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("imdb_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("original_language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("original_title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("overview")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("popularity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("poster_path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("production_companies")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("production_countries")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("release_date")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("revenue")
                        .HasColumnType("integer");

                    b.Property<float>("runtime")
                        .HasColumnType("real");

                    b.Property<string>("spoken_languages")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("tagline")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("video")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("vote_average")
                        .HasColumnType("real");

                    b.Property<int>("vote_count")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("deneme");
                });
#pragma warning restore 612, 618
        }
    }
}
